#pragma once
/* All fixed UI text lives here; the font generator extracts this inventory. */
#define TXT_TITLE "蛙声跳跳"
#define TXT_TAGLINE "说一句，跳多高？"
#define TXT_READY "等你开口"
#define TXT_LISTEN "正在听你说"
#define TXT_THINK "青蛙蓄力中"
#define TXT_RESULT "这次得分"
#define TXT_SHORT "再多说一会儿"
#define TXT_QUIET "声音太轻啦"
#define TXT_AUDIO "麦克风暂不可用"
#define TXT_INPUT "按键暂不可用"
#define TXT_HOLD "按住 OK 说话"
#define TXT_RELEASE "松开评分"
#define TXT_WAIT "马上起跳！"
#define TXT_RETRY "按住 OK 再试一次"
#define TXT_REBOOT "请重启设备"
#define TXT_LIFT "请先松开 OK"
#define TXT_FUN "随机趣味评分 · 最高 100 分"
#define TXT_BEST "最佳"
#define TXT_UNIT "分"
#define TXT_KEYS "上键重跳 / 下键归位"
#define TXT_LIMIT "最长 10 秒"
#define TXT_ZERO "零分也可爱，再来！"
#define TXT_LOW "小小一跳，也很棒"
#define TXT_MID "呱！跳得真不错"
#define TXT_HIGH "太棒了，跃上云端"
#define TXT_FULL "满分！池塘冠军"
