#pragma once
#define TXT_TITLE "声调雷达"
#define TXT_READY "等待旋律"
#define TXT_LISTEN "正在倾听"
#define TXT_MAJOR "大调"
#define TXT_MINOR "小调"
#define TXT_UNCERTAIN "调性待确认"
#define TXT_SHORT "片段太短"
#define TXT_QUIET "有效音符不足"
#define TXT_FEW "音符种类不足"
#define TXT_CLIP "声音过大"
#define TXT_ERROR "采集不可用"
#define TXT_HUM "哼唱"
#define TXT_MUSIC "音乐"
#define TXT_HUM_HELP "适合清唱或单旋律乐器"
#define TXT_MUSIC_HELP "适合播放带伴奏音乐"
#define TXT_CANDIDATE_MAJOR "候选大调"
#define TXT_CANDIDATE_MINOR "候选小调"
#define TXT_HOLD "按住 OK 听取旋律"
#define TXT_RELEASE "松开判定 / 最长 30 秒"
#define TXT_SUGGEST "建议完整旋律 8-20 秒"
#define TXT_RETRY_SHORT "请持续至少 3 秒"
#define TXT_RETRY_QUIET "靠近声源后重试"
#define TXT_RETRY_FEW "请唱出更多不同音符"
#define TXT_RETRY_CLIP "远离声源后重试"
#define TXT_RETRY_ERROR "按住 OK 重试采集"
#define TXT_REFERENCE "估计结果 / 仅供参考"
#define TXT_LIMIT "已达 30 秒 / 松开重试"
#define TXT_KEYS "上 切换模式    下 清空"
#define TXT_MATCH "匹配"
#define TXT_ALTERNATIVE "备选"
#define TXT_NOT_UNIQUE "候选接近 / 继续完整旋律"
#define TXT_LOW_MATCH "匹配偏低 / 请重新倾听"
