#!/usr/bin/env python3
"""Generate the exact UI inventory and two uncompressed LVGL 9 bitmap fonts."""
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / "main/frog_text.h").read_text()
strings = re.findall(r'^#define TXT_\w+ "([^"]*)"', source, re.M)
chars = sorted(set("".join(strings) + "".join(chr(i) for i in range(32, 127))))
inventory = "".join(chars)
(ROOT / "assets/fonts/frog-characters.txt").write_text(inventory + "\n")
(ROOT / "main/frog_glyphs.h").write_text(
    "/* Generated by tools/generate_frog_fonts.py. */\n#pragma once\n"
    "#include <stdint.h>\nstatic const uint32_t FROG_GLYPHS[] = {\n    "
    + ", ".join(f"0x{ord(c):04X}" for c in chars) + "\n};\n")
for size in (14, 20):
    subprocess.run([
        str(ROOT / ".tools/node_modules/.bin/lv_font_conv"),
        "--font", "assets/fonts/NotoSansCJKsc-Regular.otf",
        "--symbols", inventory, "--size", str(size), "--bpp", "4",
        "--format", "lvgl", "--no-compress", "--no-kerning",
        "--lv-font-name", f"frog_font_{size}", "--lv-include", "lvgl.h",
        "--output", f"assets/fonts/frog_font_{size}.c",
    ], cwd=ROOT, check=True)
    output = ROOT / f"assets/fonts/frog_font_{size}.c"
    output.write_text(output.read_text().rstrip() + "\n")
print(f"Generated {len(chars)} glyphs at 14 and 20 px")
