#!/usr/bin/env python3
"""Reproduce Q15 FFT coefficients without third-party dependencies."""
import math
from pathlib import Path

n = 4096
lines = [f'/* Generated by tools/generate_key_tables.py; Q15, N={n}. */',
         '#pragma once', '#include <stdint.h>',
         f'static const int16_t key_hann[{n}] = {{']
values = [round(32767 * (0.5 - 0.5 * math.cos(2 * math.pi * i / (n - 1)))) for i in range(n)]
for i in range(0, n, 16):
    lines.append('    ' + ', '.join(map(str, values[i:i + 16])) + ',')
lines += ['};', f'static const int16_t key_twiddle[{n // 2}][2] = {{']
for i in range(n // 2):
    lines.append('    {%d, %d},' % (round(32767 * math.cos(-2 * math.pi * i / n)),
                                  round(32767 * math.sin(-2 * math.pi * i / n))))
lines += ['};', '']
Path(__file__).resolve().parents[1].joinpath('main/key_tables.h').write_text('\n'.join(lines))
