#!/usr/bin/env python3
"""Generate app glyph inventory and two LVGL 9 font subsets (lv_font_conv 1.5.3)."""
from pathlib import Path
import re
import subprocess

root = Path(__file__).resolve().parents[1]
source = (root / 'main/key_text.h').read_text()
strings = re.findall(r'^#define TXT_\w+ "([^"]*)"', source, re.M)
chars = sorted(set(''.join(strings) + ''.join(chr(i) for i in range(32, 127))))
inventory = ''.join(chars)
(root / 'assets/fonts/key-characters.txt').write_text(inventory + '\n')
(root / 'main/key_glyphs.h').write_text(
    '/* Generated by tools/generate_key_fonts.py. */\n#pragma once\n#include <stdint.h>\n'
    'static const uint32_t KEY_GLYPHS[] = {\n    '
    + ', '.join(f'0x{ord(c):04X}' for c in chars) + '\n};\n')
converter = root / '.tools/node_modules/.bin/lv_font_conv'
assert subprocess.check_output([str(converter), '--version'], text=True).strip() == '1.5.3'
for size in (14, 20):
    subprocess.run([str(converter), '--font', 'assets/fonts/NotoSansCJKsc-Regular.otf',
                    '--symbols', inventory, '--size', str(size), '--bpp', '4',
                    '--format', 'lvgl', '--no-compress', '--no-kerning',
                    '--lv-font-name', f'key_font_{size}', '--lv-include', 'lvgl.h',
                    '--output', f'assets/fonts/key_font_{size}.c'], cwd=root, check=True)
    path = root / f'assets/fonts/key_font_{size}.c'
    path.write_text(path.read_text().rstrip() + '\n')
print(f'Generated {len(chars)} glyphs at 14/20 px')
